"""empty message

Revision ID: 245b4808716d
Revises: bcd9120cb034
Create Date: 2019-09-29 19:32:33.050618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245b4808716d'
down_revision = 'bcd9120cb034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comments_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'comments_count')
    # ### end Alembic commands ###
