"""empty message

Revision ID: 2975d2312ebc
Revises: efb4b1ad0d4b
Create Date: 2019-09-28 18:15:37.442591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2975d2312ebc'
down_revision = 'efb4b1ad0d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cm_category', sa.Column('introduce', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cm_category', 'introduce')
    # ### end Alembic commands ###
