"""empty message

Revision ID: 4553300c6a6b
Revises: 5a5b9317722c
Create Date: 2019-09-27 17:10:29.846994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4553300c6a6b'
down_revision = '5a5b9317722c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['cm_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('post', 'status')
    op.drop_column('post', 'title')
    op.drop_constraint('post_like_ibfk_2', 'post_like', type_='foreignkey')
    op.create_foreign_key(None, 'post_like', 'comment', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_like', type_='foreignkey')
    op.create_foreign_key('post_like_ibfk_2', 'post_like', 'cm_user', ['user_id'], ['id'])
    op.add_column('post', sa.Column('title', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('post', sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('images')
    # ### end Alembic commands ###
