"""empty message

Revision ID: bcd9120cb034
Revises: 2975d2312ebc
Create Date: 2019-09-29 19:21:26.188913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd9120cb034'
down_revision = '2975d2312ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('like_counts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'like_counts')
    # ### end Alembic commands ###
