"""empty message

Revision ID: c013ec43aee6
Revises: 57313f90880d
Create Date: 2019-10-01 12:00:37.091614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c013ec43aee6'
down_revision = '57313f90880d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_like_ibfk_2', 'post_like', type_='foreignkey')
    op.create_foreign_key(None, 'post_like', 'cm_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_like', type_='foreignkey')
    op.create_foreign_key('post_like_ibfk_2', 'post_like', 'comment', ['user_id'], ['id'])
    # ### end Alembic commands ###
