"""empty message

Revision ID: c16b5cdd7c63
Revises: eb107e1b1cc2
Create Date: 2019-09-27 18:21:49.632764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c16b5cdd7c63'
down_revision = 'eb107e1b1cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('images_ibfk_2', 'images', type_='foreignkey')
    op.drop_constraint('images_ibfk_3', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'post', ['post_id'], ['id'])
    op.drop_column('images', 'user_id')
    op.drop_column('images', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_ibfk_3', 'images', 'comment', ['comment_id'], ['id'])
    op.create_foreign_key('images_ibfk_2', 'images', 'cm_user', ['user_id'], ['id'])
    op.drop_column('images', 'post_id')
    # ### end Alembic commands ###
