"""empty message

Revision ID: cdd74bec7737
Revises: f1472c49a3eb
Create Date: 2019-10-05 00:28:23.026867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdd74bec7737'
down_revision = 'f1472c49a3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_likes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['cm_user.id'], )
    )
    op.alter_column('comment', 'content',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'content',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.drop_table('comments_likes')
    # ### end Alembic commands ###
