"""empty message

Revision ID: e6460c7d2f0b
Revises: 7a6b10b17b76
Create Date: 2019-09-26 22:58:37.964533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6460c7d2f0b'
down_revision = '7a6b10b17b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cm_user', sa.Column('like', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cm_user', 'like')
    # ### end Alembic commands ###
