"""empty message

Revision ID: eb107e1b1cc2
Revises: 4553300c6a6b
Create Date: 2019-09-27 18:20:13.338034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb107e1b1cc2'
down_revision = '4553300c6a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.drop_constraint('images_ibfk_1', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'comment', ['comment_id'], ['id'])
    op.drop_column('images', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_ibfk_1', 'images', 'post', ['post_id'], ['id'])
    op.drop_column('images', 'comment_id')
    # ### end Alembic commands ###
