"""empty message

Revision ID: ec41b9063ebc
Revises: e6460c7d2f0b
Create Date: 2019-09-27 02:28:04.365977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec41b9063ebc'
down_revision = 'e6460c7d2f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'reason')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('reason', mysql.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
