"""empty message

Revision ID: efb4b1ad0d4b
Revises: c16b5cdd7c63
Create Date: 2019-09-28 18:05:52.685438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efb4b1ad0d4b'
down_revision = 'c16b5cdd7c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_url', mysql.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
